import type { Metadata } from "next";
import { Footer } from "@/components/layout/Footer";
import { Header } from "@/components/layout/Header";
import { GalleryCard } from "@/components/gallery/GalleryCard";
import { listApprovedGalleryItineraries } from "@/lib/supabase/itineraryRequests";

export const revalidate = 300;

export const metadata: Metadata = {
  title: "Community Trip Ideas: Real Georgia Itineraries",
  description:
    "Browse real, AI-planned Georgia itineraries shared by other travelers — day-by-day routes across Tbilisi, Kazbegi, Svaneti, Kakheti, and more.",
  alternates: { canonical: "/trip-ideas/community" },
};

export default async function CommunityGalleryPage() {
  const itineraries = await listApprovedGalleryItineraries();

  return (
    <div className="flex min-h-screen flex-col">
      <Header />
      <main className="flex-1">
        <div className="container py-10">
          <div className="mx-auto max-w-3xl space-y-3 text-center">
            <p className="text-sm font-semibold uppercase tracking-wide text-amber-700">
              Community trip ideas
            </p>
            <h1 className="font-serif text-4xl font-semibold tracking-tight text-foreground">
              Real Georgia Itineraries, Shared by Travelers
            </h1>
            <p className="text-muted-foreground">
              Every trip below was generated by our AI planner and shared by the traveler who
              built it. Browse for inspiration, then customize any of them for your own dates.
            </p>
          </div>

          {itineraries.length > 0 ? (
            <div className="mx-auto mt-10 grid max-w-6xl gap-6 sm:grid-cols-2 lg:grid-cols-3">
              {itineraries.map((item) => (
                <GalleryCard key={item.shortId} item={item} />
              ))}
            </div>
          ) : (
            <p className="mx-auto mt-12 max-w-md text-center text-sm text-muted-foreground">
              No community trip ideas yet — check back soon, or{" "}
              <a href="/#trip-planner" className="font-medium text-primary underline">
                build your own itinerary
              </a>{" "}
              and be the first to share one.
            </p>
          )}
        </div>
      </main>
      <Footer />
    </div>
  );
}
